steps:
  - id: "Installing Go"
    name: "gcr.io/cloud-builders/go"
    args: ["install", "./src"]
    env: ["PROJECT_ROOT=main"]

  - id: "Testing"
    name: "gcr.io/cloud-builders/go"
    args: ["test", "./src"]
    env: ["PROJECT_ROOT=main"]

  - id: "Building image from Dockerfile.prod"
    name: "gcr.io/cloud-builders/docker"
    args: ["build","-t","gcr.io/$PROJECT_ID/go-cicd:$SHORT_SHA","-f","Dockerfile.prod","./src"]

  - id: "Pushing image"
    name: "gcr.io/cloud-builders/docker"
    args: ["push","gcr.io/$PROJECT_ID/go-cicd:$SHORT_SHA"]
  
  - id: "Adjusting deployment file - k8s"
    name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "/bin/sh"
    args:
      - "-c"
      - |
        sed "s#rafaelcmd/go-hpa:latest#gcr.io/$PROJECT_ID/go-cicd:$SHORT_SHA#g" deployment.yaml > deployment-new.yaml;
        cat deployment-new.yaml

  - id: "Deploying k8s"
    name: "gcr.io/cloud-builders/kubectl"
    args:
      - "apply"
      - "-f"
      - "deployment-new.yaml"
    env:
    - "CLOUDSDK_COMPUTE_ZONE=us-central1-c"
    - "CLOUDSDK_CONTAINER_CLUSTER=docker-go-cicd"
